name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Clean previous build
      run: rm -rf build && mkdir build

    - name: Set up CMake
      run: sudo apt-get update && sudo apt-get install cmake -y

    - name: Create Build Directory
      run: mkdir build

    - name: Run CMake
      run: cmake .

    - name: Build
      run: make

    - name: Run Executable
      run: ./InMemoryDB <<< "EXIT"  # Just launches and exits cleanly
